apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: nguyenquangdoan27092004/order-service:1.0
        ports:
        - containerPort: 8082
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/order_db"
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: service-urls
              key: USER_SERVICE_URL
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: service-urls
              key: PRODUCT_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
  - port: 8082
    targetPort: 8082
