apiVersion: v1
kind: ConfigMap
metadata:
  name: service-urls
  namespace: ecommerce
data:
  USER_SERVICE_URL: "http://user-service:8080"
  PRODUCT_SERVICE_URL: "http://product-service:8081"
  ORDER_SERVICE_URL: "http://order-service:8082"
  